### ISSUE TITLE
[FEAT]: Add keyboard shortcuts

### ISSUE THREAD

**Issue by hoang-himself** [Smithienious/dotfiles#8]
### Description

[zsh tutorial 1](https://dev.to/ecologic/using-keyboard-shortcuts-with-zsh-16b)
[zsh tutorial 2](https://dev.to/ecologic/passing-a-parameter-to-a-zsh-keyboard-shortcut-1877)

**Comment by Smithienious** [comment]
[Control character](https://en.wikipedia.org/wiki/Control_character#How_control_characters_map_to_keyboards)

[Caret notation](https://en.wikipedia.org/wiki/Caret_notation)

**Comment by Smithienious** [comment]
[Example](https://github.com/Phantas0s/.dotfiles/blob/master/zsh/bindings.zsh)

**Comment by Smithienious** [comment]
Done https://github.com/Smithienious/dotfiles/commit/e2f96f7f040995955ea4f76c4ec64d2bfef354ce
